// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResponseType indicates what kind of response this is
type ResponseType int32

const (
	ResponseType_RESPONSE_TYPE_UNSPECIFIED ResponseType = 0
	ResponseType_RESPONSE_TYPE_MESSAGE     ResponseType = 1 // Normal message response
	ResponseType_RESPONSE_TYPE_TOOL_RESULT ResponseType = 2 // Tool execution result
	ResponseType_RESPONSE_TYPE_ERROR       ResponseType = 3 // Error response
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "RESPONSE_TYPE_UNSPECIFIED",
		1: "RESPONSE_TYPE_MESSAGE",
		2: "RESPONSE_TYPE_TOOL_RESULT",
		3: "RESPONSE_TYPE_ERROR",
	}
	ResponseType_value = map[string]int32{
		"RESPONSE_TYPE_UNSPECIFIED": 0,
		"RESPONSE_TYPE_MESSAGE":     1,
		"RESPONSE_TYPE_TOOL_RESULT": 2,
		"RESPONSE_TYPE_ERROR":       3,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

// ChunkType indicates what kind of chunk this is
type ChunkType int32

const (
	ChunkType_CHUNK_TYPE_UNSPECIFIED ChunkType = 0
	ChunkType_CHUNK_TYPE_MESSAGE     ChunkType = 1 // Message chunk
	ChunkType_CHUNK_TYPE_END         ChunkType = 2 // End of stream
	ChunkType_CHUNK_TYPE_ERROR       ChunkType = 3 // Error chunk
)

// Enum value maps for ChunkType.
var (
	ChunkType_name = map[int32]string{
		0: "CHUNK_TYPE_UNSPECIFIED",
		1: "CHUNK_TYPE_MESSAGE",
		2: "CHUNK_TYPE_END",
		3: "CHUNK_TYPE_ERROR",
	}
	ChunkType_value = map[string]int32{
		"CHUNK_TYPE_UNSPECIFIED": 0,
		"CHUNK_TYPE_MESSAGE":     1,
		"CHUNK_TYPE_END":         2,
		"CHUNK_TYPE_ERROR":       3,
	}
)

func (x ChunkType) Enum() *ChunkType {
	p := new(ChunkType)
	*p = x
	return p
}

func (x ChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[1].Descriptor()
}

func (ChunkType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[1]
}

func (x ChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkType.Descriptor instead.
func (ChunkType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

// Request represents a client request to the agent
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                                             // Protocol version (e.g., "1.0")
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Unique request ID (UUID)
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // ISO 8601 timestamp
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                                                                               // Method name ("process", "execute", "stream")
	AgentName     string                 `protobuf:"bytes,5,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`                                                        // Target agent name (optional)
	Messages      []*Message             `protobuf:"bytes,6,rep,name=messages,proto3" json:"messages,omitempty"`                                                                           // Messages for processing
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	ToolCall      *ToolCall              `protobuf:"bytes,8,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`                                                           // Tool execution request (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Request) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Request) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

// Response represents a server response
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                                             // Protocol version
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Request ID being responded to
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // ISO 8601 timestamp
	Type          ResponseType           `protobuf:"varint,4,opt,name=type,proto3,enum=agenkit.ResponseType" json:"type,omitempty"`                                                        // Response type
	Message       *Message               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Response message (for process)
	ToolResult    *ToolResult            `protobuf:"bytes,6,opt,name=tool_result,json=toolResult,proto3" json:"tool_result,omitempty"`                                                     // Tool execution result (for execute)
	Error         *Error                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error details (if failed)
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Response) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_RESPONSE_TYPE_UNSPECIFIED
}

func (x *Response) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Response) GetToolResult() *ToolResult {
	if x != nil {
		return x.ToolResult
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StreamChunk represents a chunk in a streaming response
type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                   // Protocol version
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                             // Request ID
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // ISO 8601 timestamp
	Type          ChunkType              `protobuf:"varint,4,opt,name=type,proto3,enum=agenkit.ChunkType" json:"type,omitempty"` // Chunk type
	Message       *Message               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                   // Message chunk (optional)
	Error         *Error                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                       // Error (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StreamChunk) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StreamChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamChunk) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *StreamChunk) GetType() ChunkType {
	if x != nil {
		return x.Type
	}
	return ChunkType_CHUNK_TYPE_UNSPECIFIED
}

func (x *StreamChunk) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamChunk) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Message represents a conversational message
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`                                                                                   // Message role (user, assistant, system, tool)
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                                             // Message content (text or JSON)
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // ISO 8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// ToolCall represents a request to execute a tool
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Tool name
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`                                                                         // Tool arguments (JSON string)
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCall) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ToolResult represents the result of tool execution
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                                            // Whether execution succeeded
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                                                   // Result data (JSON string)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error message (if failed)
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ToolResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResult) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Error represents an error response
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                 // Error code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                           // Human-readable error message
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\aagenkit\"\xdf\x02\n" +
	"\aRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x05 \x01(\tR\tagentName\x12,\n" +
	"\bmessages\x18\x06 \x03(\v2\x10.agenkit.MessageR\bmessages\x12:\n" +
	"\bmetadata\x18\a \x03(\v2\x1e.agenkit.Request.MetadataEntryR\bmetadata\x12.\n" +
	"\ttool_call\x18\b \x01(\v2\x11.agenkit.ToolCallR\btoolCall\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x02\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.agenkit.ResponseTypeR\x04type\x12*\n" +
	"\amessage\x18\x05 \x01(\v2\x10.agenkit.MessageR\amessage\x124\n" +
	"\vtool_result\x18\x06 \x01(\v2\x13.agenkit.ToolResultR\n" +
	"toolResult\x12$\n" +
	"\x05error\x18\a \x01(\v2\x0e.agenkit.ErrorR\x05error\x12;\n" +
	"\bmetadata\x18\b \x03(\v2\x1f.agenkit.Response.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\vStreamChunk\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12&\n" +
	"\x04type\x18\x04 \x01(\x0e2\x12.agenkit.ChunkTypeR\x04type\x12*\n" +
	"\amessage\x18\x05 \x01(\v2\x10.agenkit.MessageR\amessage\x12$\n" +
	"\x05error\x18\x06 \x01(\v2\x0e.agenkit.ErrorR\x05error\"\xce\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12:\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1e.agenkit.Message.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\bToolCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\x12;\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1f.agenkit.ToolCall.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\n" +
	"ToolResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12=\n" +
	"\bmetadata\x18\x04 \x03(\v2!.agenkit.ToolResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\adetails\x18\x03 \x03(\v2\x1b.agenkit.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x80\x01\n" +
	"\fResponseType\x12\x1d\n" +
	"\x19RESPONSE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESPONSE_TYPE_MESSAGE\x10\x01\x12\x1d\n" +
	"\x19RESPONSE_TYPE_TOOL_RESULT\x10\x02\x12\x17\n" +
	"\x13RESPONSE_TYPE_ERROR\x10\x03*i\n" +
	"\tChunkType\x12\x1a\n" +
	"\x16CHUNK_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHUNK_TYPE_MESSAGE\x10\x01\x12\x12\n" +
	"\x0eCHUNK_TYPE_END\x10\x02\x12\x14\n" +
	"\x10CHUNK_TYPE_ERROR\x10\x032\xb9\x01\n" +
	"\fAgentService\x12.\n" +
	"\aProcess\x12\x10.agenkit.Request\x1a\x11.agenkit.Response\x129\n" +
	"\rProcessStream\x12\x10.agenkit.Request\x1a\x14.agenkit.StreamChunk0\x01\x12>\n" +
	"\x13BidirectionalStream\x12\x10.agenkit.Request\x1a\x11.agenkit.Response(\x010\x01B-Z+github.com/agenkit/agenkit-go/proto/agentpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_agent_proto_goTypes = []any{
	(ResponseType)(0),   // 0: agenkit.ResponseType
	(ChunkType)(0),      // 1: agenkit.ChunkType
	(*Request)(nil),     // 2: agenkit.Request
	(*Response)(nil),    // 3: agenkit.Response
	(*StreamChunk)(nil), // 4: agenkit.StreamChunk
	(*Message)(nil),     // 5: agenkit.Message
	(*ToolCall)(nil),    // 6: agenkit.ToolCall
	(*ToolResult)(nil),  // 7: agenkit.ToolResult
	(*Error)(nil),       // 8: agenkit.Error
	nil,                 // 9: agenkit.Request.MetadataEntry
	nil,                 // 10: agenkit.Response.MetadataEntry
	nil,                 // 11: agenkit.Message.MetadataEntry
	nil,                 // 12: agenkit.ToolCall.MetadataEntry
	nil,                 // 13: agenkit.ToolResult.MetadataEntry
	nil,                 // 14: agenkit.Error.DetailsEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	5,  // 0: agenkit.Request.messages:type_name -> agenkit.Message
	9,  // 1: agenkit.Request.metadata:type_name -> agenkit.Request.MetadataEntry
	6,  // 2: agenkit.Request.tool_call:type_name -> agenkit.ToolCall
	0,  // 3: agenkit.Response.type:type_name -> agenkit.ResponseType
	5,  // 4: agenkit.Response.message:type_name -> agenkit.Message
	7,  // 5: agenkit.Response.tool_result:type_name -> agenkit.ToolResult
	8,  // 6: agenkit.Response.error:type_name -> agenkit.Error
	10, // 7: agenkit.Response.metadata:type_name -> agenkit.Response.MetadataEntry
	1,  // 8: agenkit.StreamChunk.type:type_name -> agenkit.ChunkType
	5,  // 9: agenkit.StreamChunk.message:type_name -> agenkit.Message
	8,  // 10: agenkit.StreamChunk.error:type_name -> agenkit.Error
	11, // 11: agenkit.Message.metadata:type_name -> agenkit.Message.MetadataEntry
	12, // 12: agenkit.ToolCall.metadata:type_name -> agenkit.ToolCall.MetadataEntry
	13, // 13: agenkit.ToolResult.metadata:type_name -> agenkit.ToolResult.MetadataEntry
	14, // 14: agenkit.Error.details:type_name -> agenkit.Error.DetailsEntry
	2,  // 15: agenkit.AgentService.Process:input_type -> agenkit.Request
	2,  // 16: agenkit.AgentService.ProcessStream:input_type -> agenkit.Request
	2,  // 17: agenkit.AgentService.BidirectionalStream:input_type -> agenkit.Request
	3,  // 18: agenkit.AgentService.Process:output_type -> agenkit.Response
	4,  // 19: agenkit.AgentService.ProcessStream:output_type -> agenkit.StreamChunk
	3,  // 20: agenkit.AgentService.BidirectionalStream:output_type -> agenkit.Response
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
